# Usa una imagen base con Python
FROM python:3.8-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia todos los archivos del proyecto al contenedor
COPY . /app

# Instala las dependencias necesarias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expón el puerto 5000 si tu aplicación lo usa
EXPOSE 5000

# Establece el comando para ejecutar tu aplicación
CMD ["python", "Proyecto_ResonancIA.py"]
