# Backend sólo (Flask + PyTorch CPU)
FROM python:3.10-slim

# Dependencias del sistema para JPEG/JP2 (útil para DICOM comprimido)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libjpeg62-turbo libopenjp2-7 gcc \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY app.py /app/

EXPOSE 5000
CMD ["python", "app.py"]
